CREATE TABLE user_account (
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL,
  registered_at TIMESTAMP WITHOUT TIME ZONE
);
